<?php

/**
 * @file
 * Contains dragomans.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dragomans_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dragomans search module.
    case 'help.page.dragomans':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dragomans Search') . '</p>';
      return $output;

    default:
  }
}
